# Generated by Django 6.1.1 on 2026-09-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Admission year, e.g. 2023-24', max_length=20, unique=True)),
                ('is_running', models.BooleanField(default=True, help_text='Untick when this batch has finished.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['-name'],
            },
        ),
    ]
